language: cpp
compiler: gcc
before_install: sudo apt-get install libboost-dev
before_script:
- autoconf --version
- autoreconf --version
- automake --version
script: ./bootstrap && ./configure && make && make check
