language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - automake
    - gcc
    - g++
    - libboost-all-dev
    - autoconf-archive
before_script:
- autoconf --version
- autoreconf --version
- automake --version
script: ./bootstrap && ./configure && make && make check
after_failure: cat ./configure
