language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - automake
            - g++-4.9
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

script: ./bootstrap && ./configure && make && make check

before_install:
  - eval "${MATRIX_EVAL}"

after_failure:
  - cat ./configure
  - autoconf --version
  - autoreconf --version
  - automake --version
  - gcc --version
  - g++ --version
