language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - boost-latest
    - autoconf-archive
before_script:
- autoconf --version
- autoreconf --version
- automake --version
script: ./bootstrap && ./configure && make && make check
