language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autoconf-archive
            - automake
            - g++-5
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - autoconf-archive
            - automake
            - clang-3.6
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./bootstrap
  - ./configure
  - make
  - make check

after_failure:
  - cat ./configure
  - autoconf --version
  - autoreconf --version
  - automake --version
