language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.55-all-dev
    - autoconf-archive
before_script:
- autoconf --version
- autoreconf --version
- automake --version
script: ./bootstrap && ./configure && make && make check
